body:
  - id: bug-description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    type: textarea
    validations:
      required: true
  - id: desired-result
    attributes:
      label: Desired Result
      placeholder: Describe the desired result.
    type: textarea
    validations:
      required: true
  - id: code
    attributes:
      description: |
        Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve)
        code example here, without the Reddit() initialization, to not leak private credentials.
        This will be automatically formatted into code, so no need for backticks.
      label: Code to reproduce the bug
      placeholder: Insert code here...
      render: Python
    type: textarea
    validations:
      required: true
  - id: credential-check
    attributes:
      description: |
        The `Reddit()` initialization in my code example does not include the following parameters to prevent credential leakage:
        `client_secret`, `password`, or `refresh_token`.
      label: My code does not include sensitive credentials
      options:
        - label: "Yes, I have removed sensitive credentials from my code."
          required: true
    type: checkboxes
  - id: logs
    attributes:
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      label: Relevant Logs
      render: Shell
    type: textarea
    validations:
      required: true
  - id: previously-worked
    attributes:
      label: This code has previously worked as intended
      multiple: false
      options:
        - "I'm not sure, I haven't used this code before."
        - "Yes"
        - "No"
    type: dropdown
    validations:
      required: true
  - id: environment
    attributes:
      description: What operating system, version, and/or environment are you working with?
      label: Operating System/Environment
      placeholder: "Example: macOS Sonoma 14.1.1"
    type: input
    validations:
      required: true
  - id: python-version
    attributes:
      description: |
        What implementation and version of Python are you working with?
        CPython is assumed unless indicated otherwise.
      label: Python Version
      placeholder: "Example: 3.12.0"
    type: input
    validations:
      required: true
  - id: asyncpraw-version
    attributes:
      description: What version of `asyncpraw` are you encountering this issue with? Obtain this by running `pip show asyncpraw`.
      label: Async PRAW Version
    type: input
    validations:
      required: true
  - id: sync-praw
    attributes:
      description: Does this issue also occur in `praw`?
      label: Does this issue occur in `praw`?
      multiple: false
      options:
        - "Yes"
        - "No"
    type: dropdown
    validations:
      required: true
  - id: anything-else
    attributes:
      description: Anything that will give us more context about the issue you are encountering!
      label: Links, references, and/or additional comments?
    type: textarea
description: File a bug report
labels: [ "bug", "unverified" ]
name: Bug Report
