jobs:
  set_active_docs:
    name: Set Active Docs
    secrets:
      READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
    uses: praw-dev/.github/.github/workflows/set_active_docs.yml@1149a76ab5ae488cdc632ce70548ec3c1a278305 # v1.3.0
name: Set Active Docs
on:
  release:
    types: [ published ]
permissions:
  contents: read
