jobs:
  tag_release:
    name: Tag Release
    uses: praw-dev/.github/.github/workflows/tag_release.yml@1149a76ab5ae488cdc632ce70548ec3c1a278305 # v1.3.0
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions:
  contents: write
